# Generated by Django 5.2.1 on 2025-06-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название заголовка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Крайний срок')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
            ],
        ),
    ]
