# Generated by Django 5.2.1 on 2025-06-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='slug',
            field=models.SlugField(default='opisanie', max_length=255, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
